### ISSUE TITLE
The current latest version leaks global variables

### ISSUE THREAD

**Issue by Andarist** [kieler/elkjs#181]
At the moment the 0.7.1 bundle accidentally refers to some global variables `g` and `f` (those are minified identifiers) because those variables were not declared by particular functions in the bundle etc. It, sort of, works because this script might usually run as a script in a sloppy mode - but this violates JavaScript's strict mode rules, so for example the bundle can't be used as a module because it fails with a `ReferenceError`

**Comment by PiDayDev** [comment]
I confirm the same error on version 0.8.1 in a React project: invoking elkjs results in this error in console
```
ReferenceError: g is not defined
    at Emd (elk-worker.min.js:5037:133)
    at Iqd (elk-worker.min.js:5685:142)
    at h.dispatch (elk-worker.min.js:5984:473)
    at h.saveDispatch (elk-worker.min.js:5984:603)
    at elk-worker.min.js:5985:162```

**Comment by Andarist** [comment]
As a workaround, this is what I do before loading Elk:
```ts
(globalThis as any).g = undefined;
(globalThis as any).i = undefined;
```

**Comment by uruuru** [comment]
Maybe the fourth point of the following section in the readme sheds further light on this: https://github.com/kieler/elkjs#faqs-and-recurring-issues
